apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharecar-reservation
  labels:
    app: sharecar-reservation
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharecar-reservation
  template:
    metadata:
      labels:
        app: sharecar-reservation
    spec:
      containers:
        - name: sharecar-reservation
          image: 052937454741.dkr.ecr.ap-southeast-2.amazonaws.com/sharecar-reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
