apiVersion: v1
kind: Service
metadata:
  name: sharecar-reservation
  labels:
    app: sharecar-reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sharecar-reservation
